//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L01._3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L01._3.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck tangent för ny beräkning - Esc Avslutar..
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lönespridning:   {0,5:N0} kr.
        /// </summary>
        internal static string Dispersion {
            get {
                return ResourceManager.GetString("Dispersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! &apos;{0}&apos; kan inte tolkas som ett värde! Testa igen..
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! En lön kan inte vara ett negativt tal eller noll..
        /// </summary>
        internal static string ErrorNegativOrZero {
            get {
                return ResourceManager.GetString("ErrorNegativOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------.
        /// </summary>
        internal static string Filler {
            get {
                return ResourceManager.GetString("Filler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medellönen:      {0,5:N0} kr.
        /// </summary>
        internal static string Medel {
            get {
                return ResourceManager.GetString("Medel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medianen:        {0,5:N0} kr.
        /// </summary>
        internal static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7}.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv in hur många löner det är: .
        /// </summary>
        internal static string Salary_Prompt {
            get {
                return ResourceManager.GetString("Salary_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange lön {0}: .
        /// </summary>
        internal static string SalaryNumber {
            get {
                return ResourceManager.GetString("SalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! Du måste ha minst 2 löner för att kunna göra en uträkning!.
        /// </summary>
        internal static string TwoSalaries {
            get {
                return ResourceManager.GetString("TwoSalaries", resourceCulture);
            }
        }
    }
}
